nataili/inference/compvis.py, nataili/inference/prompt_weights.py, worker/jobs/stable_diffusion.py
For example:
A photograph of an (astronaut:1.2) riding a horse on the moon
I've been looking for a good code example to add prompt weights, but most implementations I found just split the prompt in subprompts, and make a weighted average of the embeddings of these subprompts. This has two disadvantages:
- Even adding a small weight tweak to one of the words changes the image completely
- Since the prompt is split, information about the context between words is lost. (which is exactly what transformers are good at)
This implementation takes a different approach; It calculates the difference between the whole prompt with and without the weighted subprompt. It takes this difference to be the contribution of the subprompt to the embedding vector, and uses this to subtly modify the original …
=> Add prompt weight support in the format of (subprompt:1.1)

worker/bridge_data/stable_diffusion.py, worker/jobs/stable_diffusion.py
Fixes bug as reported in:
https://github.com/db0/AI-Horde/issues/133
If the 'inpainting' model is selected for either a txt2img or img2img generation, the worker would automatically select another model (at the end of the model list).
If this model so happens to be a post-processor, the generation would fail because these can't be used as model directly. If this happens too often in a row, the worker would be put in maintenance mode.
=> [bug] enabling inpainting occasionally puts worker in maintenance mode

worker/workers/framework.py
The main-loop would break every iteration. This would be caught by an outer shutdown loop, but because this would break out of a `with ThreadPoolExecutor:` scope, it would wait for all threads to finish before starting a new thread or even getting new requests in the queue.
=> Fix queueing and threading, significantly improving performance

ldm/modules/attention.py
The existing code doesn't allow Xformers to be loaded for CUDA version 6.1 GPUs (Pascal), even though they are supported. This new code corrects that, so that Pascal GPUs can use Xformers. Tested and working on my 1080ti.
=> Fixing xformers support for Pascal GPUs

README.md
Fix 'disable-voodoo' parameter name. github.dev automatically removed trailing spaces from lines
=> Fix 'disable-voodoo' parameter name

worker/jobs/poppers.py
E.g.: `Job pop took 0.719272 (node: stablehorde:7001:3.9.1)`
=> Include horde node in job pop debug log.

model-stats.py
```text
python .\model-stats.py -h
usage: model-stats.py [-h] [-t] [-y] [-d] [-m]
Generate local worker or horde model usage statistics
options:
-h, --help        show this help message and exit
-t, --today       Local statistics for today only
-y, --yesterday   Local statistics for yesterday only
-d, --horde       Show statistics for the entire horde for the day
-m, --hordemonth  Show statistics for the entire horde for the month
```
=> Adds support for new server stats to model-stats

bridge_stable_diffusion.py, requirements.txt, worker/jobs/stable_diffusion.py
v0.2.9006 nataili adds controlnet to super manager, allowing controlnet manager to be passed into CompVis, and avoid downloading the Controlnet model database on each generation
Minimum version for Nataili set in requirements.txt, this should help with environments not updating, recommend minimum version of nataili is bumped when appropriate.
This version of AI-Horde-Worker in combination with v0.2.9006 Nataili is running on my worker.
=> Prevent downloading controlnet reference on each generation

environment.yaml, requirements.txt, runtime.cmd, update-runtime.cmd, update-runtime.sh
Makes the dependencies for conda much simpler to deal with, especially since the old file: method broke.
Now the scripts just run pip manually for a more sustainable way, this does still need testing on Linux.
So merge it after its been successfully tested.
In the future both environments.yml and requirements.txt are very minimal containing only the essentials, so most of the management can be done upstream on the nataili package.
=> Conda Overhaul

update-runtime.cmd
Turns out on the Windows side you have the same bug as on Linux where the first conda installation fails if the environment did not exist yet.
To fix this it now installs it twice on a new installation, since most of the dependencies are done by PIP and nothing is redownloaded this has minimal impact.
=> Conda workaround for Windows (Same as Linux)

worker/argparser/framework.py, worker/argparser/stable_diffusion.py
This switch enables the model cache, the alternative to ray for use when loading huge numbers of models.
=> Adds comand line option --enable_model_cache

worker/workers/stable_diffusion.py
Closes #75 
We were counting "safety_checker" and others as "loaded models" so users got a misleading error about "we don't allow workers serving unrecognized models" in the case where the real the problem was no models being served at all.
=> Fix bug with detecting number of loaded models.

worker/stats.py
Someone pointed out if the worker takes a long time to start the kudos per hour calculation is off when the worker first starts. This fixes that.
=> Fix kudos per hour accuracy at startup

.gitignore, bridge_stable_diffusion.py, worker/argparser/framework.py, worker/bridge_data/framework.py
Deprecate `--skip_md5` without immediately breaking bridge scripts.
=> update checksum args after MD5 deprecation

worker/ui.py
When running as a part of the worker with `enable_terminal_ui: true` we no longer open the log file, instead we hook Loguru directly. This prevents errors when the log file is rotated.
=> fix: terminal ui doesn't read log file.

style.py
A bug slipped in where ruff was being called with `--diff` causing it to silently fail and not produce linting results.
I assumed ruff was reporting the results when I made the change to show diffs, when in fact it was black. 
This correct the issue.
=> fix: Build/CI not running ruff correctly

bridge_scribe.py, bridge_stable_diffusion.py, show_available_models.py, worker/bridge_data/scribe.py, worker/bridge_data/stable_diffusion.py, worker/jobs/poppers.py, worker/jobs/scribe.py, worker/stats.py, worker/workers/framework.py, worker/workers/scribe.py
- Corrects the control net preloading to only occur when control_net is true in the worker config.
- Brings style/lint up to date with established rules.
=> fix: defers cn annotator check until after config is loaded

bridgeData_template.yaml, webui.py
- This brings the webui.py module up to date with the available options in the comfy branch.
- This includes the VRAM/RAM free options, and the new Scribe options.
- Also shows already downloaded models.
- If `AIWORKER_CACHE_HOME` is set, that is used. Direct users which use this environment variable to set it before invoking.
- Otherwise, the working directory (`./`) is checked for a 'nataili' folder.
- This is a mild convenience feature for users who may want to minimize disk space, but potentially have historically run features such as dynamic models.
=> feat: webui.py: now up to date with comfy config options, shows already downloaded models

webui.py
This adjusts the webui to not write out the default values for dreamer_name, alchemist_name, or scribe_name.
=> fix; improved behavior in webui for default worker names

.gitignore, .vscode/settings.json, worker/jobs/interrogation.py, worker/jobs/stable_diffusion.py
I usually use `-m6` to get a slightly more reduced filesize. This isn't a quality trade-off, it's an encoding time trade-off[^2]
[^2]: iirc from my testing a couple years ago, the extra time it takes on my 10yo PC is only noticeable with animations and mass-conversions, occasionally with big photos. ~~also 🖕 ty 🖕 Google 🖕 for making such a small limit on image dimensions, i wanted to convert my webtoon collection to webp, but the images are too tall🖕🖕🖕🖕🖕...what are you gonna do when we get 100mp cameras? oh, wait, we already have those...~~
I *think* autofilter (for the deblocking filter, iirc) would also provide better results[^1], but pillow doesn't support that option, and same with sharp_yuv.
I actually started looking at this stuff because of crap image quality I was seeing, but now …
=> add slightly better compression

webui.py
Fixes regression with the last patch which failed to capture any variables in webui other than 'models_to_load'.
=> fix: capture all other keys than 'models_to_load' in webui

worker/bridge_data/stable_diffusion.py
This should be in line with the intended 30s timeout for ad-hoc loras, but there is still a chance the largest LoRas will cause a timeout.
=> fix: increase initial LoRa download time to 900 secs

worker/bridge_data/stable_diffusion.py
If a network failure to github had occurred during this call, the worker would have abended. This corrects the issue.
See diff for more info.
=> fix: handle `get_all_models()`'s requests.get call to github if network problems occur

requirements.txt
- Includes the clipfree workaround
- Pins horde_model_reference to minor version in anticipation of upcoming breaking changes.
=> feat: hordelib to at least v1.5.1

worker/jobs/poppers.py
If the relevant function fails in without an exception, `img_data` is addressed before being assigned. This PR creates a fallback position (defines it as `None` to start).
=> fix: don't hard fail if some non-exception failure happens in `download_image_data`

worker/jobs/kudos.py, worker/jobs/stable_diffusion.py, worker/post_process.py, worker/ui.py
Some legacy behavior remapped `image_is_control` when submitting a generation payload to hordelib. This changes this behavior to match what hordelib now expects (which is what AI-Horde is returning anyway).
This is in anticipation of the hordelib patch which will enable this feature. For now, it should not cause any incompatibility as hordelib was already tolerating this being sent without specific support on its side.
=> fix: future support for image_is_control for controlnet

requirements.txt
To support the upcoming https://github.com/jug-dev/hordelib/pull/20 release having a beta window.
=> chore: temp pin hordelib (to 1.5.x)

worker/enums.py, worker/jobs/framework.py, worker/jobs/stable_diffusion.py, worker/workers/framework.py
In my experience so far, this tends to cascade, possibly due to memory leaking once the first one occurs. Further, the worst-case jobs that may precipitate this tend to happen in clusters, causing the worker to fail repeatedly.
As of this change, if more than 10 OutOfMemoryErrors occur, the worker will halt to mitigate the issue. It is not unheard of for a few OutOfMemoryErrors, but at the point of 10 (and therefore 10 failed jobs), the worker needs to be looked at as it isn't going to fix itself at this point in time.
=> fix: stop worker on continued OutOfMemoryError exceptions

webui.py, worker/bridge_data/stable_diffusion.py
This would have prevented the confusion of at least one worker, based on their report the previous behavior caused their intended desire to have `All models` loaded (in the usual way) not work as expected because `dynamic_models` was true, and `number_of_dynamic_models` was 0. 
The deeper problem at hand may need further addressing, but for now, as of this changeset:
- If `dynamic_models` is `True`, but `number_of_dynamic_models` is not set or `0`, the worker will give a warning and disable dynamic models.
- If `dynamic_models` is `True`, but there are more `models_to_load` than `number_of_dynamic_models`, the worker will give a warning and disable dynamic models.
Also, incidentally, I only just noticed a bug I had introduced a while back with webui. See …
=> fix: disable `dynamic_models` if `number_of_dynamic_models` not set/is 0

worker/ui.py
- There was a regression at some point (probably my fault) which caused the number of models loaded to show the number of all models across all types in the model count on the UI.
- The alchemy worker would create a warning that was confusing to the end user, this has been addressed.
- Additionally, the alchemy worker and the scribe worker now have specific handling (see diff) to display model counting in the UI.
=> fix: different worker type model counts, prevent warning in alchemist

bridge_alchemy.py, bridge_scribe.py, bridge_stable_diffusion.py, worker/bridge_data/interrogation.py
- [fix: do not prompt to dl alchemy models](https://github.com/Haidra-Org/AI-Horde-Worker/commit/00615d3e67d5d77f401adc71754ff3ad5b2cad43)
- I am making the executive decision to just default to downloading with no prompt the PP/clip/blip models if its just the alchemy worker running.
- [fix: have all worker types import AIWORKER_CACHE_HOME early](https://github.com/Haidra-Org/AI-Horde-Worker/commit/9f8af058ac07c32c983c093797c16ed1e1b73fb9)
- One day, in the far flung future, a proper worker refactor would eliminate the need for the *very* sensitive import orders we see.
- [fix: use updated load_model_managers method](https://github.com/Haidra-Org/AI-Horde-Worker/commit/769ab04db0e67d841f592ca4abee6ed951cb051d)
=> fix: alchemy not working if models corrupt/missing

requirements.txt, worker/workers/framework.py, worker/workers/stable_diffusion.py
See #268 for some background.
This change will:
- Instigate a worker 'soft restart', forcibly unloading all compvis models in certain situations:
- If a job is stale
- If an impossible number of models are reported as being in VRAM
- If more than 15 soft restarts occur, the worker is halted.
- Tracks `consecutive_failed_jobs` across soft restarts.
=> fix: VRAM mismanagement band-aid

bridgeData_template.yaml, webui.py, worker/bridge_data/framework.py, worker/bridge_data/stable_diffusion.py, worker/jobs/framework.py, worker/workers/framework.py, worker/workers/stable_diffusion.py
New as of this PR:
- On worker start, a single job ('pilot job') of the max configured resolution will run. (IE, 1024x1024 for max_power 32).
- If post processing is enabled, it also attempts to do a 4x upscale.
- If either of these fail, the worker will exit with an error message to this effect.
- If a job takes 3x or longer than the kudos reward in seconds, the worker will now warn that the jobs in question are probably slower than the worker operator intends.
- If they *do* intend this, they can silence the messages with the `suppress_speed_warnings` setting in bridgeData.
Fixes:
- Webui now properly reports three configurations of model folders in `AIWORKER_CACHE_HOME` which hordelib otherwise supports
- The soft restart procedure now correctly loads all the models available in disk …
=> feat: run pilot job on start, notify when jobs seem slower than would be expected

runtime.cmd
Unexpected issues around mamba not being able to init the shell have arose. This attempts to address the problem.
Micromamba was unable to actually 'enter' the virtual environment. The error was generally buried in most user outputs and was easy to miss. It probably failed in a more complex way on machines which already had a python install in their PATH.
This issue is likely limited to windows, but I remain uncertain.
Additionally, this updates the micromamba version used to the latest version for windows, which was already the case on linux.
=> fix: attempts to address new issues with install

bridge_alchemy.py, bridge_scribe.py, bridge_stable_diffusion.py, worker/utils/set_envs.py
Relying on the env var `HORDE_MAX_LORA_CACHE` for the default was leading to the purge procedure taking effect on start up.
=> fix: loras no longer delete down to 10gig on startup

requirements.txt
Of note, gradio/fastapi (part of webui) was borked when resolving to pydantic 2.0+
=> fix: prevent downstream dep issues with pydantic 2.0

bridge-preload-models.cmd, bridge-preload-models.sh, preload_models.py, worker/utils/set_envs.py
Running `bridge-preload-models.sh|.cmd` will attempt to download all the models_to_load and build the disk cache for them. This may sidestep issues with new workers running into problems with the pilot job. The future worker version (using the SDK) should end up being immune to this problem, but this serves as a stop gap for the problem, and a potential convenience in general.
=> feat: Preload models (download + build disk cache) script

runtime.cmd, update-runtime.cmd
This should allow install paths for the worker with spaces in them to work.
=> fix: allow spaces in file paths

bridge_stable_diffusion.py
This will prevent any unforeseen/undefined interactions.
=> fix: exit on legacy lora move

bridge_stable_diffusion.py, requirements.txt
No action needed unless you updated as of today; most workers can ignore the set of updates today.
=> fix: undo lora cache preserve fix attempt

worker/ui.py
worker/ui.py:163:60: E721 Do not compare types, use `isinstance()`
=> style: Fix style.sh error in worker/ui.py

requirements.txt, worker/jobs/scribe.py
This fixes the `AttributeError: 'CLIPTokenizer' object has no attribute 'split_special_tokens'` error that has cropped up with updated/new workers.
This is specifically for hordelib 1.6.2; transformers 4.30.2 is shown to not crash, where as 4.32.0 on seems to introduce a breaking change regarding the use of the aforementioned attribute causing an crash originating from within comfy.
=> fix: prevent 'CLIPTokenizer' object has no attribute 'split_special_tokens' error

requirements.txt
All workers should `git pull` and `update-runtime` soon.
If you are a worker who does not want to do so, but wishes to apply the security fix, run the following in your `AI-Horde-Worker` folder:
```bash
runtime python -s -m pip install -U Pillow
```
See https://pillow.readthedocs.io/en/stable/releasenotes/10.0.1.html for more information.
=> fix: security issue with pillow+webp

worker/ui.py
In certain environments, curses will fail to initialize properly. This includes certain docker and other containerized setups. This change will detect if a valid terminal handle is not received, and if so, default to the behavior of `disable_terminal_ui: true` (no curses).
Thanks @henk717 for bringing this to my attention.
=> fix do not crash if curses failed to init

bridgeData_template.yaml, worker/bridge_data/stable_diffusion.py
Workers, particularly those who use meta modifiers, will get errors about failing to load SDXL models when options such as `all` are choosen. This sets the default to skip it for meta modifiers, and if it is specifically loaded an error will appear (and still be skipped).
=> fix: do not attempt to load SDXL models

worker/bridge_data/scribe.py, worker/jobs/poppers.py
Various batching LLM backends with KAI support exist, making multithreaded scribe workers viable.
This patch removes the 1-thread restriction on scribes and reports thread count to horde.
Several workers are already using this modification to host multi-threaded workers on horde.
=> Multi-threaded scribe
