Haidra-Org/AI-Horde-Worker

- nataili/model_manager.py
- webui.py
- worker/jobs/poppers.py
> Update WebUI to allow up to 10 threads

- nataili/model_manager.py
- worker/jobs/poppers.py
Updates the model manager to load Blip into cpu at full precision
> Cpu Only Worker Fix

- worker/jobs/stable_diffusion.py
Fixes sd2depth and inpainting models that would crash fatally if tiling requests came through
> Fix to prevent tiling from crashing workers

- nataili/inference/compvis.py
- worker/jobs/poppers.py
Allows the horde to use the DPM++ SDE Sampler
> Add SDE Sampler

- ldm/models/diffusion/kdiffusion.py
- ldm2/models/diffusion/ddim.py
- ldm2/models/diffusion/ddpm.py
- ldm2/models/diffusion/dpm_solver/dpm_solver.py
- ldm2/models/diffusion/plms.py
- nataili/inference/compvis.py
- nataili/util/logger.py
- worker/bridge_data/framework.py
- worker/jobs/framework.py
- worker/jobs/poppers.py
- worker/jobs/stable_diffusion.py
> Make output to terminal less messy

- model-stats.py
Optional "--today" parameter causes stats to only be output based on today's data.
Optional "--yesterday" parameter causes stats to only be output based on yesterday's data.
Closes #34
> Add basic model statistics script

- worker/bridge_data/framework.py
> Reload model database if we find an unknown model

- worker/jobs/poppers.py
This header isn't always present.
> Fix: handle missing horde-node in job pop headers.

- worker/bridge_data/framework.py
Revert the previous changes. See #48
> Revert fix model reload

- worker/jobs/stable_diffusion.py
> remove sd2.x restrictions

- environment.yaml
- requirements.txt
`>=` behavior causes issues at the moment, going to hard pinning for now
> Specific version pin for nataili

- bridgeData_template.yaml
- worker/bridge_data/framework.py
- worker/jobs/stable_diffusion.py
- worker/stats.py
Doesn't display only every minute as per the issue, as then it's really hard to find the output on the screen. Displays every iteration.
Closes #79
> Display estimated average kudos per hour.

- worker/bridge_data/stable_diffusion.py
> Ensure SD model is loaded first using "ALL MODELS"

- worker/jobs/stable_diffusion.py
- worker/post_process.py
This PR allows for a facefixer_strength parameter to be passed through from the horde, and sent through to nataili as strength to tweak the post-processors
> Face fixer strength

- bridge_stable_diffusion.py
> Display version numbers when checking nataili

- .github/workflows/lint.yml
- model-stats.py
- style.py
- webui.py
- worker/bridge_data/framework.py
- worker/bridge_data/stable_diffusion.py
- worker/csam.py
- worker/jobs/interrogation.py
- worker/jobs/poppers.py
- worker/jobs/stable_diffusion.py
- worker/workers/framework.py
- worker/workers/stable_diffusion.py
- A number of refactorings, comprehensions, etc.
- Apply Black formatting to files that weren't affected before it was made into a GitHub Workflow
- Apply consistent isort to files that didn't already have it
> Refactorings, Optimizations, and Formatting

- bridge_stable_diffusion.py
- pop-stats.py
```usage: pop-stats.pY [-h] [-t] [-y] [-1]
options:
-h, --help       show this help message and exit
-t, --today      Statistics for today only
-y, --yesterday  Statistics for yesterday only
-1, --hour       Statistics for last hour only```
```
> Adds pop-stats.py script. Ugly but works.

- worker/jobs/stable_diffusion.py
This is a user input issue and does not indicate an error with the worker; INFO is more appropriate.
> change log level for inpainting model switch

- pop-stats.py
- style.py
- webui.py
- worker/ui.py
In light of merging #149, I still had some refactorings to include mentioned here: https://github.com/db0/AI-Horde-Worker/pull/149#issuecomment-1488744708
> Manual Refactorings

- environment.yaml
- worker/ui.py
This fixes the lag in cudatoolkit version pinning in `environment.yaml`.
> fix: cudatoolkit to 11.8

- README.md
- bridgeData_template.yaml
- webui.py
- worker/__init__.py
- worker/argparser/framework.py
- worker/argparser/interrogation.py
- worker/argparser/stable_diffusion.py
- worker/bridge_data/framework.py
- worker/bridge_data/stable_diffusion.py
To be merged into the comfy branch when the version of `hordelib` without these settings is available.
> fix: remove obsolete config settings

- bridge_alchemy.py
- bridge_stable_diffusion.py
- pyproject.toml
- webui.py
- worker/bridge_data/framework.py
- worker/bridge_data/stable_diffusion.py
- worker/jobs/interrogation.py
- worker/jobs/poppers.py
- worker/jobs/stable_diffusion.py
- worker/post_process.py
This brings the comfy development branch up to date with style/lint rules.
> style: development in progress style catch up

- bridge_stable_diffusion.py
- worker/workers/stable_diffusion.py
See https://github.com/jug-dev/hordelib/pull/160 for more info.
This merge should be deferred until the changes in hordelib make it into pypi.
> feat: now attempts to preload all controlnet annotators

- bridgeData_template.yaml
Also added a bit about the models_to_skip being ignored for TOP n models
> Change bridgeData to new domain name

- benchmark.sh
- environment.yaml
- nataili
- requirements.txt
> Revert to cuda 11.7 as linux has trouble finding the libraries with 11.8

- bridge_stable_diffusion.py
- show_available_models.py
- worker/jobs/stable_diffusion.py
- worker/workers/stable_diffusion.py
See https://github.com/Haidra-Org/hordelib/pull/272 for more information.
Closes #205
> fix: 'unsupport' diffusers, fixes 'ckpt' not found error

- stable-horde-worker.service_template
- Added systemd service template to more easily control running worker processes.
> adding systemd service template with some instructions

- webui.py
* Corrects an oversight preventing certain models, particularly those in the already download models list, from saving when selected in the webui.
* Some minor code cleanup, removes some dead-end or obsolete code.
> fix: already downloaded models now correctly save in webui

- webui.py
Mr. Kollmeier would disapprove of my failure to include the units here.
> fix: clarifies the unit for ram/vram to keep free

- .github/workflows/release.yml
- README.md
- pyproject.toml
- worker/bridge_data/stable_diffusion.py
Some additional references will need to be updated, but may represent a breaking change at this time.
> chore: update some of the hardcoded github urls to use haidra-org

- requirements.txt
See #258 for more info about the upcoming changes.
> chore: pin horde_clipfree in anticipation of breaking changes

- horde-alchemist-bridge.cmd
- horde-bridge.cmd
- horde-scribe-bridge.cmd
- runtime.cmd
- update-runtime.cmd
This is becoming trying random things at this point. I am unclear what, when or how the issue arises. I was able to reproduce the runtime not finding packages correctly at one point, but the prior patch had fixed it for me. This is a continued effort towards trying to narrow down the problem on other machines.
> fix: further bug fixes to install process

- bridgeData_template.yaml
Uncommenting these lines to skip sd15/sd21 creates invalid yaml
> Remove commas after models in commented models_to_delete section

- requirements.txt
https://github.com/Haidra-Org/hordelib/releases/tag/v1.6.6 is the intended version
> fix: use correct hordelib TI patch version

- webui.py
- worker/jobs/poppers.py
- worker/utils/gpuinfo.py
For high GPU count text workers, this will free up some space in the terminal UI
> feat: `AIWORKER_UI_SHOW_N_GPUS` to limit GPU UI display

- worker/jobs/scribe.py
First git PR, be gentle.
Tested for a day with aphrodite. Changes halve worker to aphrodite traffic, overall http jobs, and aphrodite console spam.
Not tested with anything else that may still use this old worker.
> Remove trailing slashes to adopt aphrodite-engine expected syntax

- README.md
- bridgeData_template.yaml
- worker/argparser/scribe.py
- worker/bridge_data/framework.py
- worker/bridge_data/scribe.py
- worker/jobs/poppers.py
- worker/jobs/scribe.py
> feat: support for openai API
